//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVTR.DVTR.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantInfo
    {
        public int ApplicantInfoId { get; set; }
        public string WorkPermitNumber { get; set; }
        public System.DateTime WorkPermitEndDate { get; set; }
        public string Health { get; set; }
        public string DriversLicense { get; set; }
        public string OwnTransport { get; set; }
        public string OtherLaguages { get; set; }
        public int PersonId { get; set; }
        public string CurrentWorkLocation { get; set; }
        public string CurrentJobTitle { get; set; }
        public string PreferredJobTitle { get; set; }
        public bool PrefJhbCbd { get; set; }
        public bool PrefJhbNorth { get; set; }
        public bool PrefJhbSouth { get; set; }
        public bool PrefJhbWest { get; set; }
        public bool PrefMidrand { get; set; }
        public bool PrefPretoria { get; set; }
        public bool RelocateRsa { get; set; }
        public bool RelocateInternational { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
