//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVTR.DVTR.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentType
    {
        public EmploymentType()
        {
            this.ApplicantContracts = new HashSet<ApplicantContract>();
            this.ApplicantContracts1 = new HashSet<ApplicantContract>();
        }
    
        public int EmploymentTypeId { get; set; }
        public string EmploymentType1 { get; set; }
    
        public virtual ICollection<ApplicantContract> ApplicantContracts { get; set; }
        public virtual ICollection<ApplicantContract> ApplicantContracts1 { get; set; }
    }
}
